// fonts src
const root = 'https://static.crunchyroll.com/vilos-v2/web/vilos/assets/libass-fonts/';

// file list
const fontFamilies = {
  'A-OTF Kakumin Pro': ['A-OTF_Kakumin_Pro_M.otf'],
  'AdLib BT': ['AdLibRg.ttf'],
  'Adobe Arabic': ['AdobeArabic-Bold.otf'],
  'Andale Mono': ['andalemo.ttf'],
  'Agency FB': ['Agencyr.ttf'],
  'Agency FB Bold': ['Agencyb.ttf'],
  'Amienne': ['Amienne.ttf'],
  'Arial': ['arial.ttf'],
  'ArialMT': ['ArialMT.ttf'],
  'Arial Bold': ['arialbd.ttf'],
  'Arial Bold Italic': ['arialbi.ttf'],
  'Arial Italic': ['ariali.ttf'],
  'Arial Unicode MS': ['arialuni.ttf'],
  'Arial Unicode MS Bold': ['arialunibd.ttf'],
  'Arial Black': ['ariblk.ttf'],
  'Arial Nova': ['ArialNova.ttf'],
  'Arial Nova Italic': ['ArialNova-Italic.ttf'],
  'Arial Nova Light': ['ArialNova-Light.ttf'],
  'Arial Nova Light Italic': ['ArialNova-LightItalic.ttf'],
  'Arial Nova Bold': ['ArialNova-Bold.ttf'],
  'Arial Nova Bold ItalicCalibri': ['ArialNova-BoldItalic.ttf'],
  'Arial Nova Cond Light': ['ArialNovaCond-Light.ttf'],
  'Arial Nova Cond Light Italic': ['ArialNovaCond-LightItalic.ttf'],
  'Arial Nova Cond': ['ArialNovaCond.ttf'],
  'Arial Nova Cond Italic': ['ArialNovaCond-Italic.ttf'],
  'Arial Nova Cond Bold': ['CalibriArialNovaCond-Bold.ttf'],
  'Arial Nova Cond Bold Italic': ['ArialNovaCond-BoldItalic.ttf'],
  'Arial Rounded MT Bold': ['arlrdbd.ttf'],
  'Arial Narrow': ['Arial_Narrow.ttf'],
  'Arial Narrow Italic': ['Arial_Narrow_Italic.ttf'],
  'Arial Narrow Bold': ['ARIALNB.ttf'],
  'Arial Narrow Bold Italic': ['Arialnbi.ttf'],
  'Bahnschrift': ['bahnschrift.ttf'],
  'Bahnschrift Light': ['bahnschrift.ttf'],
  'BakerSignet BT': ['BAKRSIGN.ttf'],
  'Balloon Bd BT': ['balloonbdbtbold.ttf'],
  'Balloon XBd BT': ['balonxb.ttf'],
  'Belwe Bd BT': ['BelweBdBTBold.ttf'],
  'BIZ UDMincho Medium': ['BIZ-UDMincho-Medium-01.ttf'],
  'BIZ UDPMincho Medium': ['BIZ-UDPMincho-Medium-02.ttf'],
  '@BIZ UDPMincho Medium': ['BIZ-UDPMincho-Medium-02.ttf'],
  'Bookshelf Symbol 7': ['Bssym7.ttf'],
  'Bolton': ['Bolton.ttf'],
  'BoltonBold': ['BoltonBold.ttf'],
  'BoltonBoldItalic': ['BoltonBoldItalic.ttf'],
  'BoltonElongated': ['BoltonElongated.ttf'],
  'BoltonItalic': ['BoltonItalic.ttf'],
  'BoltonLight': ['BoltonLight.ttf'],
  'BoltonLightItalic': ['BoltonLightItalic.ttf'],
  'Bradley Hand ITC': ['BRADHITC.ttf'],
  'Canuth': ['Canuth.ttf'],
  'Cheltenhm BdCn BT Bold': ['Cheltenhm_BdCn_BT_Bold.ttf'],
  'Calibri': ['Calibri.ttf'],
  'Calibri Bold Italic': ['Calibri_Bold_Italic.ttf'],
  'Calibri Bold': ['Calibri_Bold.ttf'],
  'Calibri Italic': ['Calibri_Italic.ttf'],
  'Calibri Light Italic': ['Calibri_Light_Italic.ttf'],
  'Calibri Light': ['Calibri_Light.ttf'],
  'Calibri Regular': ['Calibri_Regular.ttf'],
  'Cambria': ['Cambria.ttf'],
  'Cambria Bold': ['cambriab.ttf'],
  'Cambria Bold Italic': ['Cambriaz.ttf'],
  'Cambria Italic': ['Cambriai.ttf'],
  'Candara': ['Candara.ttf'],
  'Caviar Dreams': ['CaviarDreams.ttf'],
  'Caviar Dreams Bold': ['CaviarDreams_Bold'],
  'Caviar Dreams Bold Italic': ['CaviarDreams_BoldItalic'],
  'Caviar Dreams Italic': ['CaviarDreams_Italic'],
  'Consolas': ['Consola.ttf'],
  'Consolas Bold': ['Consolab.ttf'],
  'Consolas Bold Italic': ['Consolaz.ttf'],
  'Consolas Italic': ['Consolai.ttf'],
  'Comic Sans MS': ['comic.ttf'],
  'comic sans MS': ['comicsansms.ttf'], 
  'comic sans ms': ['comicsansms.ttf'],
  'Comic Sans MS Bold': ['comicbd.ttf'],
  'Cooper Black': ['Cooper_Black_Regular.ttf'],
  'Courier': ['Courier_Regular.ttf'],
  'Courier Bold': ['Courier_BOLD.ttf'],
  'Courier Italic': ['Courier_Italic.ttf'],
  'Courier Bold Italic': ['Courier_Bold_Italic.ttf'],
  'Courier New': ['cour.ttf'],
  'courier new': ['cour.ttf'],
  'Courier New Bold': ['courbd.ttf'],
  'Courier New Bold Italic': ['courbi.ttf'],
  'Courier New Italic': ['couri.ttf'],
  'Corbel': ['Corbel.ttf'],
  'Corbel Bold': ['Corbelb.ttf'],
  'Corbel Bold Italic': ['Corbelz.ttf'],
  'Corbel Italic': ['Corbeli.ttf'],
  'Corbel Light': ['Corbell.ttf'],
  'Corbel Light Italic': ['Corbelli.ttf'],
  'Cherry Caramel':['Cherry_Caramel.ttf'],
  'Chiller':['Chiller.ttf'],
  'David': ['david.ttf'],
  'David Bold': ['davidbd.ttf'],
  'DejaVu LGC Sans Mono Bold': ['DejaVuLGCSansMono-Bold.ttf'],
  'DejaVu LGC Sans Mono Bold Oblique': ['DejaVuLGCSansMono-BoldOblique.ttf'],
  'DejaVu LGC Sans Mono Oblique': ['DejaVuLGCSansMono-Oblique.ttf'],
  'DejaVu LGC Sans Mono': ['DejaVuLGCSansMono.ttf'],
  'DejaVu Sans Bold': ['DejaVuSans-Bold.ttf'],
  'DejaVu Sans BOLd': ['DejaVuSans-Bold.ttf'],
  'DejaVu Sans Bold Oblique': ['DejaVuSans-BoldOblique.ttf'],
  'DejaVu Sans ExtraLight': ['DejaVuSans-ExtraLight.ttf'],
  'DejaVu Sans Oblique': ['DejaVuSans-Oblique.ttf'],
  'DejaVu Sans': ['DejaVuSans.ttf'],
  'DejaVu Sans Condensed Bold': ['DejaVuSansCondensed-Bold.ttf'],
  'DejaVu Sans Condensed Bold Oblique': ['DejaVuSansCondensed-BoldOblique.ttf'],
  'DejaVu Sans Condensed Oblique': ['DejaVuSansCondensed-Oblique.ttf'],
  'DejaVu Sans Condensed': ['DejaVuSansCondensed.ttf'],
  'DejaVu Sans Mono Bold': ['DejaVuSansMono-Bold.ttf'],
  'DejaVu Sans Mono Bold Oblique': ['DejaVuSansMono-BoldOblique.ttf'],
  'DejaVu Sans Mono Oblique': ['DejaVuSansMono-Oblique.ttf'],
  'DejaVu Sans Mono': ['DejaVuSansMono.ttf'],
  'Dot Font': ['DOTFONT.ttf'],
  'DomCasual BT': ['domcasn.ttf'],
  'DK Ruby Red': ['DK_Ruby_Red.otf'],
  'ErasBoldITC': ['ErasBoldITC.ttf'],
  'Ebrima': ['Ebrima_Regular.ttf'],
  'Ebrima Bold': ['Ebrima_Bold.ttf'],
  'Eras Medium ITC': ['Erasmd.ttf'],
  'Eraser': ['Eraser_Regular.ttf'],
  'FinkSans': ['FinkSans_Regular.ttf'],
  'FirstGrader': ['first_grader.ttf'],
  'FC-GyoKaishotai': ['FC-GyoKaishotai.ttf'],
  'Franklin Gothic Book': ['Franklin_Gothic_Book_Regular.ttf'],
  'Freehand471 BT': ['FRHND471.ttf'],
  'Gautami': ['Gautami.ttf'],
  'Gabriola': ['Gabriola.ttf'],
  'Garamond': ['Garamond_Regular.ttf'],
  'Georgia': ['georgia.ttf'],
  'Georgia Bold': ['georgiab.ttf'],
  'Georgia Italic': ['georgiai.ttf'],
  'Georgia Bold Italic': ['georgiaz.ttf'],
  'Gill Sans': ['Gill_Sans.otf'],
  'Gill Sans Bold Italic': ['Gill_Sans_Bold_Italic.otf'],
  'Gill Sans Bold': ['Gill_Sans_Bold.otf'],
  'Gill Sans Heavy Italic': ['Gill_Sans_Heavy_Italic.otf'],
  'Gill Sans Heavy': ['Gill_Sans_Heavy.otf'],
  'Gill Sans Italic': ['Gill_Sans_Italic.otf'],
  'Gill Sans Light Italic': ['Gill_Sans_Light_Italic.otf'],
  'Gill Sans Light': ['Gill_Sans_Light.otf'],
  'Gill Sans Medium Italic': ['Gill_Sans_Medium_Italic.otf'],
  'Gill Sans Medium': ['Gill_Sans_Medium.otf'],
  'Gill Sans Condensed Bold': ['Gill_Sans_Condensed_Bold.otf'],
  'Gill Sans Condensed': ['Gill_Sans_Condensed.otf'],
  'Gloucester MT Extra Condensed': ['Glecb.ttf'],
  'Helvetica': ['Helvetica.ttf'],
  'Helvetica Bold': ['Helvetica-Bold.ttf'],
  'Helvetica Bold Oblique': ['Helvetica-Bold-Oblique.ttf'],
  'Helvetica Compressed': ['Helvetica-compressed.ttf'],
  'Helvetica Light': ['Helvetica-light.ttf'],
  'Helvetica Oblique': ['Helvetica-Oblique.ttf'],
  'Helvetica Rounded Bold': ['Helvetica-rounded-bold.ttf'],
  'Incised901 BT': ['INC901K.ttf'],
  'Incised901 Bd BT': ['Incised_901_Bold_BT.ttf'],
  'Incised901 Lt BT': ['Inc901Lt.ttf'],
  'Impact': ['impact.ttf'],
  'impact': ['impact.ttf'],
  'Ink Free': ['Inkfree.ttf'],
  'Kristen ITC': ['ITCKRIST.ttf'],
  'Lato ExtraBold': ['Lato-ExtraBold.ttf'],
  'Liberation Mono': ['LiberationMono-Regular.ttf'],
  'Liberation Mono Bold': ['LiberationMono-Bold.ttf'],
  'Liberation Mono Bold Italic': ['LiberationMono-BoldItalic.ttf'],
  'Liberation Mono Italic': ['LiberationMono-Italic.ttf'],
  'LinotypeFinnegan Medium': ['linotypefinnegan-medium.ttf'],
  'Lucida Calligraphy': ['Lucida_Calligraphy_Font.ttf'],
  'Lucida Console': ['Lucida_Console.ttf'],
  'Lucida Sans': ['Lsans.ttf'],
  'Lucida Sans Italic': ['Lsansi.ttf'],
  'Lucida Sans Demibold Roman': ['Lsansd.ttf'],
  'Lucida Sans Demibold Italic': ['Lsansdi.ttf'],
  'Marâtre': ['Marâtre.otf'],
  'Mead Bold': ['Mead_Bold.ttf'],
  'Meera Inimai': ['MeeraInimai-Regular.ttf'],
  'Microsoft New Tai Lue': ['Ntailu.ttf'],
  'Microsoft New Tai Lue Bold': ['Ntailub.ttf'],
  'Microsoft Sans Serif': ['micross.ttf'],
  'MS Gothic': ['MS-Gothic-01.ttf'],
  'MS PGothic': ['MS_PGothic.ttf'],
  'MS Mincho': ['MS-Mincho-01.ttf'],
  'MS PGothic Bold': ['MS-PGothic-03.ttf'],
  'MS PMincho': ['MS-PMincho-02.ttf'],
  'MS UI Gothic': ['MS-UIGothic-02.ttf'],  
  'MS Sans Serif': ['micross.ttf'],
  'Noto Sans Thai': ['NotoSansThai-Regular.ttf'],
  'Noto Sans Thai Bold': ['NotoSansThai-Bold.ttf'],
  'Noto Sans Telugu': ['NotoSansTeluguVariable.ttf'],
  'Noto Sans Tamil': ['NotoSansTamilVariable.ttf'],
  'Monotype Corsiva': ['Mtcorsva.ttf'],
  'Onyx': ['Onyx.ttf'],
  'Open Sans Bold': ['OpenSans-Bold.ttf'],
  'Open Sans Bold Italic': ['OpenSans-BoldItalic'],
  'Open Sans Extrabold': ['OpenSans-ExtraBold.ttf'],
  'Open Sans Extrabold Italic': ['OpenSans-ExtraBoldItalic'],
  'Open Sans Italic': ['OpenSans-Italic.ttf'],
  'Open Sans Light': ['OpenSans-Light'],
  'Open Sans Light Italic': ['OpenSans-LightItalic.ttf'],
  'Open Sans Regular': ['OpenSans-Regular'],
  'Open Sans Semibold': ['OpenSans-Semibold'],
  'Open Sans Semibold Italic': ['OpenSans-SemiboldItalic.ttf'],
  'Palatino Linotype': ['Pala.ttf'],
  'Palatino Linotype Bold': ['Palab.ttf'],
  'Palatino Linotype Bold Italic': ['Palabi.ttf'],
  'Pristina': ['Pristina.ttf'],
  'Rambla': ['Rambla-Regular.ttf'],
  'Rambla Italic': ['Rambla-Italic.ttf'],
  'Rambla Bold': ['Rambla-Bold.ttf'],
  'Rambla Bold italic': ['Rambla-BoldItalic.ttf'],
  'Ravie': ['Ravie.otf'],
  'Replay': ['Replay.ttf'],
  'Rubik Black': ['Rubik-Black.ttf'],
  'Rubik Black Italic': ['Rubik-BlackItalic.ttf'],
  'Rubik Bold': ['Rubik-Bold.ttf'],
  'Rubik Bold Italic': ['Rubik-BoldItalic.ttf'],
  'Rubik Italic': ['Rubik-Italic.ttf'],
  'Rubik Light': ['Rubik-Light.ttf'],
  'Rubik Light Italic': ['Rubik-LightItalic.ttf'],
  'Rubik Medium': ['Rubik-Medium.ttf'],
  'Rubik Medium Italic': ['Rubik-MediumItalic.ttf'],
  'Rubik': ['Rubik-Regular.ttf'],
  'Segoe Script': ['Segoe_Script.ttf'],
  'Segoe Print': ['Segoepr.ttf'],
  'Staccato222 BT': ['Staccato222_BT.ttf'],
  'Segoe Print Bold': ['Segoeprb.ttf'],
  'Staccato555 BT': ['Staccato555BT-RegularA.otf'],
  'squeaky chalk sound': ['SqueakyChalkSound.ttf'],
  'Square721 Dm': ['Square721DmNormal.ttf'],
  'Square 721 Blk': ['Square721BlkNormal.ttf'],
  'Swis721 BT': ['Swiss-721-BT-Font.ttf'],
  'Tahoma': ['tahoma.ttf'],
  'Tempus Sans ITC': ['Tempsitc.ttf'],
  'Terminal': ['Terminal.ttf'],
  'Timeless': ['Timeless.ttf'],
  'Timeless Bold': ['Timeless-Bold.ttf'],
  'Times New Roman': ['times.ttf'],
  'Times New Roman Bold': ['timesbd.ttf'],
  'Times New Roman BOLd': ['timesbd.ttf'],
  'Times New Roman Bold Italic': ['timesbi.ttf'],
  'Times New Roman Italic': ['timesi.ttf'],
  'Tonic': ['Tonic_Regular.ttf'],
  'Trebuchet MS': ['trebuc.ttf'],
  'trebuchet ms': ['trebuc.ttf'],
  'Trebuchet MS Bold': ['trebucbd.ttf'],
  'Trebuchet MS Bold Italic': ['trebucbi.ttf'],
  'Trebuchet MS Italic': ['trebucit.ttf'],
  'Tw Cen MT Condensed': ['Tw-Cen-MT-Condensed-Font.ttf'],
  'VAGRounded BT': ['VAGRoundedBT.ttf'],
  'Verdana': ['verdana.ttf'],
  'verdana': ['verdana.ttf'],
  'Verdana Bold': ['verdanab.ttf'],
  'Verdana Italic': ['verdanai.ttf'],
  'Verdana Bold Italic': ['verdanaz.ttf'],
  'Vrinda': ['vrinda.ttf'],
  'Vrinda Bold': ['vrindab.ttf'],
  'Webdings': ['webdings.ttf'],
  'Yu Gothic Bold': ['YuGothic-Bold-01.ttf'],
  'Yu Gothic Light': ['YuGothic-Light-01.ttf'],
  'Yu Gothic Medium': ['YuGothic-Medium-01.ttf'],
  'Yu Gothic Regular': ['YuGothic-Regular-01.ttf'],
  'Yu Gothic UI': ['YuGothicUI-Bold-02.ttf'],
  'Yu Gothic UI Light': ['YuGothicUI-Light-02.ttf'],
  'Yu Gothic UI Regular': ['YuGothicUI-Regular-02.ttf'],
  'Yu Gothic UI Semibold': ['YuGothicUI-Semibold-03.ttf'],
  'Yu Gothic UI Semilight': ['YuGothicUI-Semilight-02.ttf'],
};

// parse ass
function assFonts(ass: string): string[] {
  const requiredFonts = new Set<string>();
  const lines = ass.replace(/\r/g, '').split('\n');

  // parse [V4+ Styles]
  for (const line of lines) {
    if (line.startsWith('Style: ')) {
      const parts = line.split(',');
      if (parts.length < 9) continue;

      const fontName = parts[1].trim();
      const isBold = parts[7].trim() === '-1';
      const isItalic = parts[8].trim() === '-1';

      requiredFonts.add(fontName);

      if (isBold && isItalic) {
        requiredFonts.add(`${fontName} Bold Italic`);
        requiredFonts.add(`${fontName} Bold`);
        requiredFonts.add(`${fontName} Italic`);
      } else if (isBold) {
        requiredFonts.add(`${fontName} Bold`);
      } else if (isItalic) {
        requiredFonts.add(`${fontName} Italic`);
      }
    }
  }

  // parse overrides
  const fontMatches = ass.matchAll(/\\fn([^\\}]+)/g);
  for (const match of fontMatches) {
    requiredFonts.add(match[1].trim());
  }

  return [...requiredFonts];
}

// font mime type
function fontMime(fontFile: string){
  if(fontFile.match(/\.otf$/)){
    return 'application/vnd.ms-opentype';
  }
  if(fontFile.match(/\.ttf$/)){
    return 'application/x-truetype-font';
  }
  return 'application/octet-stream';
}

export type AvailableFonts = keyof typeof fontFamilies;

// output
export { root, fontFamilies, assFonts, fontMime };